server:
  port: 8185

spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/auth_db}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.security: trace