server :
  port : 8186

spring :
  application:
    name: hr-planning-service

  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:8888

  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true
    properties :
      hibernate :
        format_sql : true

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/hr-planning_db}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver
