spring:
  output:
    ansi:
      enabled: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

ip-address: 172.20.85.83

keycloak:
  server-url: http://${ip-address}:8282
  realm: saas-erp
  client-id: saas-client
  client-secret: APHalzvUVsfz9Jffe5ZAZ1XImFwv5a8K
  openIdConnectUrl: ${keycloak.server-url}/realms/${keycloak.realm}/.well-known/openid-configuration

springdoc:
  swagger-ui:
    path: /swagger-ui
    oauth:
      client-id: ${keycloak.client-id}
      client-secret: ${keycloak.client-secret}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${ip-address}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ip-address}:9411/api/v2/spans
  info:
    git:
      mode: full
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      client:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      default:
        timeout-duration: 3s
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 5s