server:
  port: 8761

spring:
  application:
    name: discovery-server

  output:
    ansi:
      enabled: always

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#  username: ${EUREKA_USERNAME:eureka}
#  password: ${EUREKA_PASSWORD:eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
  info:
    git:
      mode: full
  metrics:
    tags:
      application: ${spring.application.name}