server :
  port : 8181

spring :
  application:
    name: organization-service

  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:8888

  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true
    properties :
      hibernate :
        format_sql : true

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/organization_db}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet :
    multipart :
      enabled : true
      file-size-threshold : 2KB
      max-file-size : 10MB
      max-request-size : 10MB