server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native

  output:
    ansi:
      enabled: always

  cloud:
    config:
      server:
        native:
          search-locations: file:/deployment/config

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
  info:
    git:
      mode: full
  metrics:
    tags:
      application: ${spring.application.name}